### PR TITLE
Pk/main/u3 Merging U2 with latest fixes from Yi

### PR DESCRIPTION
**Pull request by phkrief**

### CODE REVIEW

**Comment by phkrief** [comment]
@chrisguindon there is a conflict with the navbar.html file because I changed one default logo size which was not consistent between the left and the right logo.
Else I'm ready for publishing and like that @flora8984461 will be able to reproduce the logo open issue.

So thanks for accepting my PR, we need to start promoting the page.

**Comment by flora8984461** [comment]
@phkrief  Just hope to make sure, did you also include my changes in styles.less (https://github.com/EclipseFdn/opensourceinnovation.eu/pull/5/files#diff-790657c7ea88aba05f7f5df53edb044c71306a48408ddb96f167f7d5fb447917)?

This also helps to keep the right logo align right. Thanks!

**Comment by phkrief** [comment]
@chrisguindon the website looks great. Could you push it to live, please?
Thanks a lot

**Comment by phkrief** [comment]
Thx a lot for your great help !!
Kind regards
*—*
Philippe Krief, PhD
Research Relations Director | Eclipse Foundation, Inc.
Eclipse Foundation <http://www.eclipse.org/>: The Platform for Open
Innovation and Collaboration
M: +33 (0)6 21 01 06 81

Annastr. 46, D-64673 Zwingenberg
Handelsregister: Darmstadt HRB 92821
Managing Directors: Gaël Blondelle, Mike Milinkovich

**Pull request merged**
