### PR TITLE
Initial draft for Open Research Webinars #1

### LINKED ISSUE #1: Open Research Webinars event website
Hi there,
The content template for this event is on the team drive on https://docs.google.com/document/d/11W7y8Cyvyazm6uzzARzNyixLNqUdmVdADfs2YB_MkxE/edit#. 

Let us know what additional information you need!

### PR DESCRIPTION
**Pull request by flora8984461**
Fix #1 

Open research webinar event page: https://deploy-preview-2--eclipsefdn-opensourceinnovation.netlify.app/2020/december/

----------------------- Updated on Nov 12 -------------------------------
revision history 0.4

 - remove Brain IoT logo
 - create a footer.html and remove some links
 - remove "edit my account"
 - remove "featured story"

------------------------ Updated on Nov 11 -----------------------------
revision history 0.3

- Replace right nav with logo (Not sure should I also remove toolbar?)
- Adjust Homepage upcoming events block (Can someone provide me design and color theme for homepage?)
- Updated all button's default color
- Updated speaker's bg
- Modified the shortcode for past events to hide past events when no one

------------------------ Updated on Nov 10 -----------------------------
revision history 0.2

- Updated header img, header text, header button, one header logo, including header text font-weight
- Add "CET" to Series Launch: Tuesday, December 15, 2020, 16:00-17:00 CET
- Hide a dash after h1
- Updated "About Us" text
- Add end_text in registeration.yml
- Also update header bg at homepage and code-of-conduct

------------------------ Updated on Nov 09 -----------------------------
revision history 0.1

TODO list for me:

- [x] header

   - title(✔)
   - subtitle(✔)
   - Tagline(✔)
   - Important links(✔ - register)

- [x] Registration (About the Event) 

   - About content (✔)
   - Important links ( what's the registeration link? )
   - End Date (✔)
   - End text 

- [x] Speakers / Program Committee

   - User_display on front page with one speaker (✔)
   - Program Committee? 
   - A page to display all speakers and User_display will hook to the person you clicked on? 

- [x] Agenda
   - default fake content created (✔)
   - Does session Information need? 

- [x] Sponsors
   - Co-organizers(✔ - copied from SAM IoT)

- [x] Webinar Series (use the homepage)

   - draft similar to jakartaOne, with upcoming events block and past events block (for now the content is empty) (✔)
   - More design... 

- [x] Fix no spacing in registeration link button on mobile view (merged by https://github.com/EclipseFdn/solstice-assets/commit/5a0a5b7dd4a91a9f7130bada635dd128db04e8fc)

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Comment by phkrief** [comment]
@flora8984461 and @chrisguindon Could you validate this PR like that I will be able to start working on it.
Thx a lot for your understanding

**Comment by flora8984461** [comment]
> @flora8984461 and @chrisguindon Could you validate this PR like that I will be able to start working on it.
> Thx a lot for your understanding

Hi @phkrief , I make it ready for review, and will defer to Chris.

Thanks!

**Review by phkrief — APPROVED** [review]

**Comment by phkrief** [comment]
@chrisguindon could you have the kindness to review and accept this PR. 
I need it to start our own changes.

Thanks a lot for your understanding

**Comment by chrisguindon** [comment]
@phkrief I will be reviewing the code with @flora8984461 today!

**Pull request merged**
