### PR TITLE
Initial update of the site

### PR DESCRIPTION
**Pull request by phkrief**
- Updating Speaker pictures
- Removing useless logos
- Updating event page with correct logos

Signed-off-by: Philippe Krief <philippe.krief@eclipse-foundation.org>

### CODE REVIEW

**Comment by phkrief** [comment]
@chrisguindon my build is failing and I can't figure out what is wrong.
I try to create a second event (for march 2021) by simply duplicate the files and folder.
If I leave the _index.md from December unchanged it works. I adapt it to 2021. It crashes...

Can you check it out, please?
Thx a lot

**Comment by chrisguindon** [comment]
> @chrisguindon my build is failing and I can't figure out what is wrong.
> I try to create a second event (for march 2021) by simply duplicate the files and folder.
> If I leave the _index.md from December unchanged it works. I adapt it to 2021. It crashes...
> 
> Can you check it out, please?
> Thx a lot

This is the error from the Netlify log:

12:55:25 PM: Error: Error building site: "/opt/build/repo/content/2021/march/_index.md:16:1": failed to render shortcode "grid/section-container": failed to process shortcode: "/opt/build/repo/node_modules/eclipsefdn-hugo-solstice-theme/layouts/shortcodes/events/registration.html:46:14": execute of template failed: template: shortcodes/events/registration.html:46:14: executing "shortcodes/events/registration.html" at <$t.Before>: can't evaluate field Before in type *errors.errorString

I will download your PR and submit a fix.

**Comment by chrisguindon** [comment]
@phkrief The issue should be fixed now. The problem was with the date format in the registration.yml file:
https://github.com/EclipseFdn/opensourceinnovation.eu/pull/4/commits/09a0cdbcb079532b15f1471c6fb9c444cb5f15ae

**Comment by phkrief** [comment]
It works! Thx a lot.
Did I make a mistake on a date, @chrisguindon ?

**Comment by phkrief** [comment]
I found your fix ! Gotcha ! Thx

**Comment by phkrief** [comment]
@chrisguindon we would like to resize the height of the logos on the header but it seems that we are limited even if I try to set the width of the logo to 350px, for example.
Can you help us fix that?
thx a lot

**Comment by chrisguindon** [comment]
@phkrief,

I think we are introducing too many changes with this PR that the logo issue should be dealt with separately. 

@flora8984461 can you please fix the logo via a new PR? As discussed, we should start by properly cropping the OW2 logo.

**Pull request closed without merging**
