### PR TITLE
Fix project icons on both events

### PR DESCRIPTION
**Pull request by phkrief**
Signed-off-by: Philippe Krief <philippe.krief@eclipse-foundation.org>

### CODE REVIEW

**Comment by phkrief** [comment]
Dear @chrisguindon ,
This PR is ready for merging

**Comment by chrisguindon** [comment]
@phkrief I will submit some changes, the speaker-guide page is listing sub-pages at the bottom:
https://deploy-preview-17--eclipsefdn-opensourceinnovation.netlify.app/speaker-guide/

**Comment by chrisguindon** [comment]
@phkrief While making the changes (https://github.com/EclipseFdn/opensourceinnovation.eu/pull/17/commits/02b75d5c80d77c81cba3f4476a968895e3e7274a), I noticed that a few links that were not working.

 I fix what I could find but can you review the site to make sure that all is well before we merge?

**Comment by phkrief** [comment]
Dear @chrisguindon ,

Good catch! I made a last minute change and forgot about the impact of this change.
i tested all the links and they work great.
So you can merge it

**Pull request merged**
